# Generated by Django 4.0.4 on 2022-05-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('info', models.CharField(max_length=250, verbose_name='Информация')),
                ('full_text', models.TextField(verbose_name='Текст')),
                ('data', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
