# Generated by Django 4.0.4 on 2022-05-25 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articl',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии '},
        ),
    ]
