# Generated by Django 4.0.4 on 2023-01-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Место работы')),
            ],
            options={
                'verbose_name': 'Место',
            },
        ),
        migrations.AddField(
            model_name='articl',
            name='place_of_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_Job', to='main.place', verbose_name='Место работы'),
        ),
    ]
